# General
seed: 1234
cuda: True

# Training
epoch: 2

# DataLoader
batch_size: 32
shuffle: True

# Dataset
dataset:
  train:
    RandomKmerDataset: {}
  valid:
    RandomKmerDataset: {}

# Model
model:
  FactorizedRNN:
    # Normal stuff
    layers_size: [150, 100]
    inputs_size: [4, 5]

    # RNN specific
    input_emb_size: 100
    hidden_size: 512
    num_layers: 2
    nb_emb: 2

# Optimizer
optimizer:
  Adam:
    lr: 0.001

# pytorch transform
transform:
  train: {}
  valid: {}